### ISSUE TITLE
No compatible version found when installing on Ubuntu with npm

### ISSUE THREAD

**Issue by scottwarnick** [maxtaco/coffee-script#158]
I had to specifically install version 1.6.3-b 
npm install -g iced-coffee-script@1.6.3-b

**Comment by maxtaco** [comment]
Do an `npm -v` and a `node -v` for me?

**Comment by ss-abramchuk** [comment]
Same problem with OS X

>bash$ npm install -g iced-coffee-script
>npm ERR! Darwin 14.4.0
>npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "iced-coffee-script"
>npm ERR! node v0.12.5
>npm ERR! npm  v2.11.2
>npm ERR! code ETARGET

>npm ERR! notarget No compatible version found: iced-coffee-script@'*'
>npm ERR! notarget Valid install targets:
>npm ERR! notarget ["1.6.3-b","1.6.3-c","1.6.3-d","1.6.3-e","1.6.3-f","1.6.3-g","1.6.3-h","1.6.3-i","1.6.3-j","1.7.0-a","1.7.1-a","1.7.1-b","1.7.1-c","1.7.1-d","1.7.1-e","1.7.1-f","1.7.1-g","1.8.0-a","1.8.0-b","1.8.0-c","1.8.0-d","1.8.0-e","1.2.0-c","1.2.0-d","1.2.0-e","1.2.0-f","1.2.0-g","1.2.0-h","1.2.0-i","1.2.0-j","1.2.0-k","1.2.0-l","1.2.0-m","1.2.0-n","1.2.0-o","1.2.0-p","1.2.0-q","1.2.0-r","1.2.0-s","1.2.0-t","1.2.0-u","1.3.1-a","1.3.1-b","1.3.1-c","1.3.3-a","1.3.3-b","1.3.3-c","1.3.3-d","1.3.3-e","1.3.3-f","1.3.3-g","1.3.3-h","1.4.0-a","1.4.0-b","1.4.0-c","1.6.2-a","1.6.2-b","1.6.2-c","1.6.2-d","1.6.3-a"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by maxtaco** [comment]
Looks like a new problem with the new NPM. For now try:

```
npm install -g iced-coffee-script@1.8.0-e
```

**Comment by maxtaco** [comment]
Should be fixed now with a new versioning system @v108.0.6.  Thanks for the feedback.
